# Generated by Django 5.2.8 on 2025-11-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_notification_tasklog_taskfollower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tasklog',
            options={'ordering': ['-timestamp']},
        ),
    ]
