# Generated by Django 5.2.1 on 2025-06-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_notification_tasklog_taskfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='change_type',
            field=models.CharField(default='initial', max_length=100),
            preserve_default=False,
        ),
    ]
